name: Jesús Sebastián Cruz
title: Full Stack Development

summary: |
  Full Stack Web Developer with over 15 years of experience developing robust and scalable web applications. Specialized in modern technologies such as React, Next.js, NestJS, Laravel, and WordPress, with a strategic focus on system architecture and development process optimization. Proven track record in mentoring and leading teams, selecting the most suitable technologies to maximize efficiency and success in high-impact projects within dynamic and demanding environments.

contact:
  title: General Information
  data:
    - label: Location
      value: Buenos Aires, Argentina
    - label: Email
      value: cruzjesussebastian@gmail.com
    - label: Phone
      value: +54 9 11 2567-6328
    - label: GitHub
      value: https://github.com/sebacruz
    - label: LinkedIn
      value: https://linkedin.com/in/sebacruz

experience:
  title: Experience
  data:
    - role: Full Stack Developer
      company: Social Snack
      period: "2009 - 2019"
      responsibilities:
        - Responsible for developing and maintaining web applications
          using Laravel and WordPress, tailoring each solution to the
          client’s needs.
        - Implemented interactive interfaces with Bootstrap and React,
          improving user experience and optimizing engagement on
          platforms with over 100,000 active users.
        - Managed Unix servers, ensuring the stability and availability
          of development and production environments.
        - Standardized development processes, improving code quality
          and operational efficiency across the team.
        - Mentored junior and mid-level developers, supporting their
          integration of modern technologies into real-world projects.

    - role: Lead Developer
      company: Chispa Lab
      period: "2019 - 2023"
      responsibilities:
        - Led the development of web applications using Next.js,
          ensuring seamless integration of REST APIs in scalable
          systems.
        - Designed backend architectures with NestJS, optimizing
          authentication and third-party service integrations.
        - Defined agile processes and utilized Docker and Kubernetes to
          ensure consistent and rapid deployments.
        - Supervised experienced developers, guiding the implementation
          of advanced technical solutions.
        - Provided technical mentorship, promoting best practices and
          helping the team resolve complex technical challenges.

skills:
  title: Skills
  data:
    - name: Frontend
      items:
        - HTML
        - CSS
        - JavaScript
        - React
        - Next.js
    - name: Backend
      items:
        - Node.js
        - NestJS
        - Laravel
        - PHP
    - name: Databases
      items:
        - MySQL
        - PostgreSQL
    - name: DevOps
      items:
        - Docker
        - Kubernetes
        - AWS
        - CI/CD
    - name: Others
      items:
        - Git
        - Unix Systems Administration
        - Memcached
        - Varnish
        - Nginx
        - REST APIs
        - Web3

projects:
  title: Featured Projects
  data:
    - name: ponty.app
      url: https://chispalab.com/projects/ponty
      technologies: [NestJS, Next.js, AWS, S3, Docker]
      description: |
        Responsible for the design and development of the backend
        architecture for an event management platform. Implemented
        microservices using NestJS to handle authentication with Auth0
        and payments with Stripe, ensuring a smooth and secure
        integration. Utilized Docker for containerization and AWS S3
        for file storage, ensuring the infrastructure was scalable and
        robust, capable of supporting continuous user growth. The
        project achieved a successful implementation, offering a fast
        and reliable user experience.

    - name: fitchin.gg
      url: https://chispalab.com/projects/fitchin
      technologies: [MySQL, NestJS, Next.js, Kubernetes]
      description: |
        Responsible for developing the backend for the Communities
        section of a gaming platform. Used NestJS to implement REST
        APIs, integrating Web3-based authentication services to ensure
        security and scalability. The system resulted in a stable and
        highly scalable platform, capable of handling activity peaks
        without compromising performance.

    - name: Super Experiencias Santander Río
      technologies: [MySQL, Laravel, React, Docker, Nginx, Memcached, Varnish]
      description: |
        Developed an internal social network for Santander Río
        employees in Argentina. Built the platform using Laravel and
        MySQL, allowing employees to rate and share work experiences.
        Configured servers with Nginx and optimized performance with
        Memcached and Varnish, handling high traffic for 150,000 users
        in Argentina and 200,000 in Spain.

    - name: socialsnack.com
      technologies: [WordPress, Nginx, Bootstrap]
      description: |
        Developed a fully manageable corporate website with WordPress,
        designed to reflect the company's identity and facilitate
        content management. The platform enables dynamic updates
        through a fully customized administration panel.

    - name: La Editorial Común
      url: https://web.archive.org/web/20160710083741/http://laeditorialcomun.com/
      technologies: [WordPress, WooCommerce, Varnish, Memcached]
      description: |
        Responsible for the frontend implementation and integration with
        WordPress and WooCommerce for the store and blog of one of the
        biggests argentinian caricaturists. Configured servers and
        optimized performance using Varnish and Memcached, ensuring a
        smooth user experience in a high-traffic environment.
